config/routes.rb
Rails.application.routes.draw do
  root "articles#index"
  resources :articles do
    member do
      post :notify_friend
    end
    resources :comments
  end
  resources :users
  resource :session, :only => [:new, :create, :destroy]
  get '/login' => "sessions#new", :as => "login"
  get '/logout' => "sessions#destroy", :as => "logout"
  

end

app/models/article.rb
class Article < ActiveRecord::Base
  validates_presence_of :title, :body
  belongs_to :user
  has_and_belongs_to_many :categories
  has_many :comments
  
  scope :published, lambda { where("articles.published_at IS NOT NULL") }
  scope :draft, lambda { where("articles.published_at IS NULL") }
  scope :recent, lambda { published.where("articles.published_at > ?", 1.week.ago.to_date) }
  scope :where_title, lambda { |term| where("articles.title LIKE ?", "%#{term}%") }
  
  def long_title
    "#{title} - #{published_at}"
  end
  
  def published?
    published_at.present?
  end
  
  def owned_by?(owner)
    return false unless owner.is_a?(User)
    user == owner
  end
  
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_and_belongs_to_many :articles
  
  default_scope lambda { order('categories.name') }
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
  
  validates_presence_of :name, :email, :body
  validate :article_should_be_published
  
  after_create :email_article_author
  
  def article_should_be_published
    errors.add(:article_id, "is not published yet") if article && !article.published?
  end
  
  def email_article_author
    puts "We will notify #{article.user.email} in Chapter 9"
  end
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
require 'digest'
class User < ActiveRecord::Base
  attr_accessor :password
  validates_uniqueness_of :email
  validates_length_of :email, :within => 5..50
  validates_format_of :email, :with =>  /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
  validates_confirmation_of :password
  validates_length_of :password, :within => 4..20
  validates_presence_of :password, :if => :password_required?
  
  has_one :profile
  has_many :articles, -> { order('published_at DESC, title ASC') }, :dependent => :destroy
  has_many :replies, :through => :articles, :source => :comments
  
  before_save :encrypt_new_password
  
  def self.authenticate(email, password)
    user = find_by_email(email)
    return user if user && user.authenticated?(password)
  end
  
  def authenticated?(password)
    self.hashed_password == encrypt(password)
  end
  
  protected
    def encrypt_new_password
      return if password.blank?
      self.hashed_password = encrypt(password)
    end
    
    def password_required?
      hashed_password.blank? || password.present?
    end
    
    def encrypt(string)
      Digest::SHA1.hexdigest(string)
    end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  protected
    def current_user
      return unless session[:user_id]
      @current_user ||= User.find_by_id(session[:user_id])
    end
    
    helper_method :current_user
    
    def authenticate
      logged_in? || access_denied
    end
    
    def logged_in?
      current_user.is_a? User
    end
    
    helper_method :logged_in?
    
    def access_denied
      redirect_to login_path, notice: "Please log in to continue" and return false
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate, except: [:index, :show]
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @title = t('articles_all')
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @title = @article.long_title
  end

  # GET /articles/new
  def new
    @title = t('article_new')
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
    @title = 'Редактирование статьи - ' + @article.title
    @article = current_user.articles.find(params[:id])
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = current_user.articles.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    @article = current_user.articles.find(params[:id])
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article = current_user.articles.find(params[:id])
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url }
      format.json { head :no_content }
    end
  end
  
  def notify_friend
    @article = Article.find(params[:id])
    Notifier.email_friend(@article, params[:name], params[:email]).deliver
    redirect_to @article, :notice => "Successfully sent a message to ypur friend"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :body, :location, :excerpt, :published_at, :category_ids=>[])
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :load_article, :except => :destroy
  before_action :authenticate, :only => :destroy
  
  def create
    @comment = @article.comments.new(comment_params)
    if @comment.save
      redirect_to @article, notice: 'Thanks for your comment'
    else
      redirect_to @article, alert: 'Unable to add comment'
    end
  end
  
  def destroy
    @article = current_user.articles.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to @article, notice: 'Comment deleted'
  end
  
  private
    def load_article
      @article = Article.find(params[:article_id])
    end
    
    def comment_params
      params.require(:comment).permit(:name, :email, :body)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    if user = User.authenticate(params[:email], params[:password])
      session[:user_id] = user.id
      redirect_to root_path, :notice => 'Logged in successfully'
    else
      flash.now[:alert] = 'Invalid login/password combination'
      render :action => 'new'
    end
  end
  
  def destroy
    reset_session
    redirect_to root_path, :notice => 'You successfully logged out'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate, only: [:edit, :update]
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to articles_path, notice: 'User successfully added.'
    else
      render action: :new
    end
  end
  
  def edit
    @user = current_user
  end
  
  def update
    @user = current_user
    if @user.update(user_params)
      redirect_to articles_path, notice: 'Updated user information successfully'
    else
      render action: 'edit'
    end
  end
  
  private
    def set_user
      @user = current_user
    end
    
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def submit_or_cancel(form, name=t('cancel'))
    form.submit( t('save'), :class => 'btn btn-success') + "  " + link_to(name, 'javascript:history.go(-1);', :class => 'btn btn-danger')
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_article.html.slim
= div_for article do
  h3
    = link_to article.title, article
    - if article.owned_by? current_user
      span class='pull-right'
        = link_to "Edit", edit_article_path(article), :class => "btn btn-primary btn-xs"
        = link_to "Delete", article, confirm: "Are you sure?", method: :delete, :class => "btn btn-danger btn-xs"
  = simple_format article.body
  hr

app/views/articles/_form.html.slim
= form_for @article do |f|
  - if @article.errors.any?
    #error_explanation
      h2 = "#{pluralize(@article.errors.count, "error")} prohibited this article from being saved:"
      ul
        - @article.errors.full_messages.each do |message|
          li = message
  div class="row"
    div class="col-lg-6"
      div class="panel panel-info"
        div class="panel-heading"
          |Create new article
        div class="panel-body"
          .field
            = f.label :title
            = f.text_field :title, :class => "form-control"
          .field
            = f.label :body
            = f.text_area :body, :class => "form-control"
          .field
            = f.label :location
            = f.text_field :location, :class => "form-control"
          .field
            = f.label :excerpt
            = f.text_field :excerpt, :class => "form-control"
          .field
            = f.label "Categories"
            - Category.all.each do |category|
              = check_box_tag 'article[category_ids][]', category.id, @article.category_ids.include?(category.id), id: dom_id(category)
              = label_tag dom_id(category), category.name, class: "check_box_label"
          .field
            = f.label :published_at
            = f.datetime_select :published_at
          .actions = submit_or_cancel(f)

app/views/articles/_notify_friend.html.erb
<%= form_tag(notify_friend_article_path(@article), :id => 'notify_friend_form',:style => 'display:none') do %>
  <div class="field">
    <%= label_tag :name, 'Your name' %><br />
    <%= text_field_tag :name %>
  </div>
  <div class="field">
    <%= label_tag :email, "Your friend's email" %><br />
    <%= text_field_tag :email %>
  </div>
  <div class="actions">
    <%= submit_tag 'Send' %> or
    <%= link_to 'Cancel', '#', :onclick => "$('#notify_friend_form').slideUp()" %>
  </div>
<% end %>

app/views/articles/edit.html.slim
h1 Editing article

== render 'form'

= link_to 'Show', @article
'|
= link_to 'Back', articles_path

app/views/articles/index.html.slim
h1 Listing articles

div id="articles"
  = render @articles

= link_to 'New Article', new_article_path, :class => 'btn btn-success'

app/views/articles/new.html.slim
== render 'form'

= link_to 'Back', articles_path

app/views/articles/show.html.slim
= render @article

= link_to 'Email a friend', '#',:onclick => "$('#notify_friend_form').slideDown()"
= render 'notify_friend'

  
h3 Comments
div id="comments"
  =render @article.comments
  
= render :file => 'comments/new'

= link_to 'Edit', edit_article_path(@article)
'|
= link_to 'Back', articles_path

app/views/comments/_comment.html.slim
= div_for comment do
  div class="row"
    div class="col-lg-6"
      div class="panel panel-default"
        div class="panel-heading"
          = comment.name
          span class="label label-info" style="font-size:70%; vertical-align: text-top;"
            = comment.email
          - if @article.owned_by? current_user
            span class='actions'
              = link_to 'Delete', [@article, comment], confirm: 'Are you sure?', method: :delete, :class => "btn btn-danger btn-xs pull-right"
        div class="panel-body"
          = comment.body

app/views/comments/new.html.slim
div class="row"
  div class="col-lg-6"
    div.well
      = form_for([@article, @article.comments.new]) do |f|
        div class="field"
          = f.label :name
          br
          = f.text_field :name, :class => "form-control"
        div class="field"
          = f.label :email
          br
          = f.text_field :email, :class => "form-control"
        div class="field"
          = f.label :body
          br
          = f.text_area :body, :class => "form-control"
        div class="actions"
          = f.submit 'Add', :class => "btn btn-success pull-right"
        br

app/views/layouts/application.html.slim
doctype html
html
  head
    title = @title
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  body
    a id="move_up" href="#"
      |Вверх

    div class="container"
      div class="row"
        div class="col-lg-12"
        
          div#header
            h1
              = link_to "бЛОГ", root_path
            div class="user_bar pull-right button-group"
              - if logged_in?
                = link_to t('article_new'), new_article_path, :class=>"btn btn-success"
                = link_to t('edit_pass'), edit_user_path(current_user), :class=>"btn btn-default"
                = link_to t('logout'), logout_path, :class=>"btn btn-danger"
              - else
                = link_to t('login'), login_path, :class=>"btn btn-success"
          div.clearfix
          = content_tag :p, notice, :class => 'alert alert-info' if notice.present?
          = content_tag :p, alert, :class => 'alert alert-danger' if alert.present?
          
          = yield
          div#footer
            |A simple blog built for the book

app/views/notifier/email_friend.text.slim
Your friend =@sender_name thinks you may like the following article:

=@article.title
|:
=article_url(@article, :host => 'localhost:3000')

app/views/users/_form.html.slim
= form_for(@user) do |f|
  - if @user.errors.any?
    div id="error_explanation"
      h2
        = pluralize(@user.errors.count, "error")
        |prohibited this user from being saved:
      ul
      - @user.errors.full_messages.each do |msg|
        li
          = msg
  div class="field"
    = f.label :email
    br
    = f.text_field :email
  div class="field"
    = f.label :password
    br
    = f.password_field :password
  div class="field"
    = f.label :password_confirmation
    br
    = f.password_field :password_confirmation
  div class="actions"
    = submit_or_cancel(f)

app/views/users/edit.html.slim
h1 Edit user
= render 'form'
= link_to 'Back'

app/views/users/new.html.slim
h1 
  |New user
= render 'form'
= link_to 'Back', articles_path